name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - uses: gradle/wrapper-validation-action@v1
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with: 
          arguments: |
              build
              --scan
    
    - name: "Add build scan URL as PR comment"
      uses: actions/github-script@v5
      if: github.event_name == 'commit'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ github.workflow }}: ${{ steps.gradle.outputs.build-scan-url }}'
          })
